

all: exec


install:
	pip install -r requirements.txt


exec:
	chmod 755 parcial-relaxada


help:
	@echo "======================== Ajuda ============================"
	@echo " [*] Para executar o programa, use: make"
	@echo " [*] Para instalar as dependências, use: make install"
	@echo " [*] Para limpar eventuais lixos, use: make clean"
	@echo "==========================================================="


clean:
	@echo "Limpeza"
	rm -rf __pycache__