
all: run
	 

run:
	chmod 755 envio


install:
	pip install -r requirements.txt


help:
	@echo "============================== Ajuda ==============================="
	@echo " [*] Para gerar o executável, use: make"
	@echo " [*] Para instalar as dependências, use: make install"
	@echo " [*] Para limpar eventuais lixos, use: make clean ou make purge"
	@echo "===================================================================="


clean:
	@echo "Limpeza"
	rm -rf __pycache__

